spring:
  datasource:
    url: jdbc:mariadb://hack.cidtckobgf3m.ap-northeast-2.rds.amazonaws.com:3306/hack
    username: root
    password: cksdl30104
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #show_sql: true
        format_sql: ture

logging.level:
  org.hibernate.SQL: debug